/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ItemType = IDL.Variant({
  'nft' : IDL.Null,
  'digitalArt' : IDL.Null,
  'craftItem' : IDL.Null,
  'physicalProduct' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Purchase = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'purchaseDate' : IDL.Nat64,
  'buyer' : IDL.Principal,
  'price' : IDL.Nat,
});
export const Item = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : IDL.Vec(IDL.Nat8),
  'description' : IDL.Text,
  'purchaseHistory' : IDL.Vec(Purchase),
  'itemType' : ItemType,
  'artist' : IDL.Principal,
  'price' : IDL.Nat,
});
export const ArtistProfile = IDL.Record({
  'name' : IDL.Text,
  'artist' : IDL.Principal,
  'gallery' : IDL.Vec(Item),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'isArtist' : IDL.Bool,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ItemType],
      [IDL.Text],
      [],
    ),
  'createNft' : IDL.Func([IDL.Text], [], []),
  'getArtistProfile' : IDL.Func([IDL.Principal], [ArtistProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItem' : IDL.Func([IDL.Text], [Item], ['query']),
  'getNftOwner' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseItem' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveItemImage' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'setArtistProfile' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ItemType = IDL.Variant({
    'nft' : IDL.Null,
    'digitalArt' : IDL.Null,
    'craftItem' : IDL.Null,
    'physicalProduct' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Purchase = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'purchaseDate' : IDL.Nat64,
    'buyer' : IDL.Principal,
    'price' : IDL.Nat,
  });
  const Item = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : IDL.Vec(IDL.Nat8),
    'description' : IDL.Text,
    'purchaseHistory' : IDL.Vec(Purchase),
    'itemType' : ItemType,
    'artist' : IDL.Principal,
    'price' : IDL.Nat,
  });
  const ArtistProfile = IDL.Record({
    'name' : IDL.Text,
    'artist' : IDL.Principal,
    'gallery' : IDL.Vec(Item),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'isArtist' : IDL.Bool,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ItemType],
        [IDL.Text],
        [],
      ),
    'createNft' : IDL.Func([IDL.Text], [], []),
    'getArtistProfile' : IDL.Func([IDL.Principal], [ArtistProfile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItem' : IDL.Func([IDL.Text], [Item], ['query']),
    'getNftOwner' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseItem' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveItemImage' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
    'setArtistProfile' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };